import ReduxProvider from "@/providers/ReduxProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import NgProgress from "../NgProgress";
import Particles from "../Particles";
import Footer from "./Footer";
import Header from "./Header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "SURGE",
	description: "Generated by Mahmoud Nabowy",
};

export default function Layout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
			>
				<Particles />

				<ToastContainer />

				<NgProgress />

				<Header />
				<main className="flex-1 mb-10">
					<ReduxProvider>{children}</ReduxProvider>
				</main>
				<Footer />
			</body>
		</html>
	);
}
